[package]
name = "apt-sources-lists"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstickman@gmail.com>"]
license = "MIT"
readme = "README.md"

[dependencies]
failure = "0.1.3"
failure_derive = "0.1.3"
